# This is default and very simple configuration file for Yasb.
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
komorebi:
  start_command: "komorebic start --ahk"
  stop_command: "komorebic stop --ahk"
  reload_command: "komorebic stop --ahk && komorebic start --ahk"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 6
      left: 6
      bottom: 0
      right: 6
    widgets:
      left: ["home", "komorebi_workspaces", "komorebi_active_layout", "apps"]
      center: ["active_window"]
      right:
        ["pomodoro", "volume", "vscode", "todo", "notifications", "power_menu"]
widgets:
  # win_button:
  #   type: "yasb.custom.CustomWidget"
  #   options:
  #     label: "\udb80\udf5c"
  #     label_alt: "\udb80\udf5c"
  #     class_name: "system-widget"
  #     callbacks:
  #       on_left: "exec start_menu"
  home:
    type: "yasb.home.HomeWidget"
    options:
      # label: "<span>󰜗</span>"
      label: "<span>\ue62a</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "~\\Downloads" }
        - { title: "Documents", path: "~\\Documents" }
        - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false
  # media:
  #   type: "yasb.media.MediaWidget"
  #   options:
  #     label: "{title}"
  #     label_alt: "{artist} - {title}"
  #     max_field_size:
  #       label: 24
  #       label_alt: 24
  #     show_thumbnail: true
  #     controls_only: false
  #     controls_left: true
  #     hide_empty: true
  #     thumbnail_alpha: 80
  #     thumbnail_padding: 24
  #     thumbnail_corner_radius: 0
  #     thumbnail_edge_fade: true
  #     icons:
  #       prev_track: "󰒮"
  #       next_track: "󰒭"
  #       play: "󰐊"
  #       pause: "󰏤"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      rewrite:
        - pattern: "^(.+?)\\.exe$"
          replacement: "\\1"
          case: "lower"
  # clock:
  #   type: "yasb.clock.ClockWidget"
  #   options:
  #     label: "{%a, %d %b %H:%M}"
  #     label_alt: "{%A, %d %B %Y %H:%M}"
  #     timezones: []
  #     callbacks:
  #       on_left: "toggle_label"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "⏼ Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
      enable_scroll_switching: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  komorebi_stack:
    type: "komorebi.stack.StackWidget"
    options:
      label_offline: "Offline"
      label_window: "{process}"
      label_window_active: "{process}"
      label_no_window: "No Window"
      label_zero_index: false
      show_icons: "always"
      icon_size: 14
      max_length: 10
      max_length_active: 20
      max_length_ellipsis: ".."
      hide_if_offline: false
      show_only_stack: false
      rewrite:
        - pattern: "^(.+?)\\.exe$"
          replacement: "\\1"
          case: "lower"
      animation: true
      enable_scroll_switching: true
      container_shadow:
        enabled: true
        color: "#000000"
        offset: [0, 1]
        radius: 2
      btn_shadow:
        enabled: true
        color: "#000000"
        offset: [0, 1]
        radius: 2
      label_shadow:
        enabled: true
        color: "#000000"
        offset: [0, 1]
        radius: 2
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximized: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"
  # weather:
  #   type: "yasb.weather.WeatherWidget"
  #   options:
  #     label: "<span>{icon}</span> {temp}"
  #     label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
  #     api_key: env
  #     update_interval: 600
  #     hide_decimal: true
  #     location: env
  #     callbacks:
  #       on_left: "toggle_label"
  #     icons:
  #       sunnyDay: ""
  #       clearNight: ""
  #       cloudyDay: ""
  #       cloudyNight: ""
  #       rainyDay: ""
  #       rainyNight: ""
  #       snowyIcyDay: ""
  #       snowyIcyNight: ""
  #       blizzardDay: "󰼶"
  #       blizzardNight: "󰼶"
  #       foggyDay: ""
  #       foggyNight: ""
  #       thunderstormDay: ""
  #       thunderstormNight: ""
  #       default: ""
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - ""
        - ""
        - ""
        - ""
        - ""
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  # microphone:
  #   type: "yasb.microphone.MicrophoneWidget"
  #   options:
  #     label: "<span>{icon}</span> {level}"
  #     label_alt: "<span>{icon}</span> {level}%"
  #     icons:
  #       normal: "󰍬"
  #       muted: "󰍭"
  #     callbacks:
  #       on_left: "toggle_mute"
  #       on_middle: "toggle_label"
  #       on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: ""
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["", "Shut Down"]
        restart: ["", "Restart"]
        signout: ["󰍃", "Sign out"]
        hibernate: ["", "Hibernate"]
        sleep: ["⏾", "Sleep"]
        cancel: ["", "Cancel"]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\uf489", launch: "wt", name: "Terminal" } # launch terminal
        - {
            icon: "\udb80\ude39",
            launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
            name: "Browser",
          }
        - { icon: "", launch: "cmd /c Taskmgr", name: "Task Manager" }
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span></span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  # systray:
  #   type: "yasb.systray.SystrayWidget"
  #   options:
  #     class_name: "systray"
  #     label_collapsed: "▼"
  #     label_expanded: "▶ "
  #     label_position: "left" # Can be "left" or "right"
  #     icon_size: 16 # Can be any integer between 8 and 64
  #     pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
  #     show_unpinned: false
  #     show_unpinned_button: true
  #     show_battery: false
  #     show_volume: false
  #     show_network: false
  #     btn_shadow:
  #       enabled: true
  #       color: "black"
  #       radius: 3
  #       offset: [ 1, 1 ]
  vscode:
    type: "yasb.vscode.VSCodeWidget"
    options:
      label: "<span>\udb82\ude1e</span>"
      label_alt: "<span>\udb82\ude1e</span> recents"
      menu_title: "<span style='font-weight:bold'>VScode</span> recents"
      max_field_size: 50
      folder_icon: "\uf114"
      file_icon: "\uf016"
      truncate_to_root_dir: false
      hide_folder_icon: false
      hide_file_icon: false
      max_number_of_folders: 30
      max_number_of_files: 30 # set to 0 if you only want folders
      modified_date_format: "Date modified: %Y-%m-%d %H:%M"
      cli_command: "code" # or "codium" or "windsurf" or any other CLI command to open the workspace
      menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        alignment: "center"
        offset_top: 0
  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "\uf501 New Task"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
